### ISSUE TITLE
Negative numbers

### ISSUE THREAD

**Issue by legagneur-matthieu** [normandesjr/jquery-mask-number#2]
Hi!
Can you add support for accept negative numbers ?
thanks !

**Comment by legagneur-matthieu** [comment]
I have find a simple fix : 

$.fn.maskNumber.defaults = {
    thousands: ",",
    decimal: ".",
    integer: false,
    allowNegative: false,
};

function format(input, settings) {
    var inputValue = input.value;
    inputValue = removeNonDigits(inputValue, settings.allowNegative);
    /*...*/
}

function removeNonDigits(value, allowNegative ) {
    return ((allowNegative && value[0] === "-") ? "-" : "") + value.replace(/\D/g, "");
}

and use : $("#my_input").maskNumber({allowNegative:true});

I send a pull request ...

**Comment by normandesjr** [comment]
Great! Done!
